----------------
--   TASK 3   --
----------------

----------------------
-- Roles definition --
----------------------

CREATE ROLE JUNIOR_SALESMAN;
CREATE ROLE SENIOR_SALESMAN;
GRANT JUNIOR_SALESMAN TO SENIOR_SALESMAN;
CREATE ROLE SALESMAN_MANAGER;
GRANT SENIOR_SALESMAN TO SALESMAN_MANAGER;
CREATE ROLE JUNIOR_WAREHOUSEMAN;
CREATE ROLE SENIOR_WAREHOUSEMAN;
GRANT JUNIOR_WAREHOUSEMAN TO SENIOR_WAREHOUSEMAN;
CREATE ROLE WAREHOUSEMAN_MANAGER;
GRANT SENIOR_WAREHOUSEMAN TO WAREHOUSEMAN_MANAGER;
CREATE ROLE TOPMANAGER;
GRANT WAREHOUSEMAN_MANAGER TO TOPMANAGER;
GRANT SALESMAN_MANAGER TO TOPMANAGER;

GRANT TOPMANAGER TO fabiola_jackson;
GRANT JUNIOR_SALESMAN TO virgie_wiggins, venita_daniel;
GRANT SENIOR_SALESMAN TO genna_serrano, marcelene_boyer;
GRANT SALESMAN_MANAGER TO mireya_copeland, jannette_david;
GRANT JUNIOR_WAREHOUSEMAN TO gabriel_howells, charlie_knight;
GRANT SENIOR_WAREHOUSEMAN TO madeleine_norton, zoe_mellor;
GRANT WAREHOUSEMAN_MANAGER TO eve_randall, isobel_price;

CREATE ROLE CUSTOMER;
GRANT CUSTOMER TO debra_burks, kasha_todd;

---------------------
-- Junior Salesman --
---------------------

CREATE OR REPLACE VIEW PRODUCT_WO_COST AS
SELECT product_id, product_name, brand_id, category_id, model_year, list_price
FROM ADMIN.PRODUCTS
ORDER BY product_name;

CREATE VIEW CUSTOMER_INFO AS
SELECT customer_id, first_name, last_name, email
FROM ADMIN.CUSTOMERS;

GRANT SELECT ON PRODUCT_WO_COST TO JUNIOR_SALESMAN;
GRANT SELECT ON ORDERS TO JUNIOR_SALESMAN;
GRANT SELECT ON ORDER_ITEMS TO JUNIOR_SALESMAN;
GRANT SELECT ON CUSTOMER_INFO TO JUNIOR_SALESMAN;

---------------------
-- Senior Salesman --
---------------------

CREATE VIEW STAFF_SALE_ACT AS
SELECT staff_id, first_name, last_name, email, phone, store_id, manager_id
FROM ADMIN.STAFFS
WHERE active = 1
  AND department = 'SALESMAN';

GRANT INSERT ON ORDERS TO SENIOR_SALESMAN;
GRANT INSERT ON ORDER_ITEMS TO SENIOR_SALESMAN;
GRANT SELECT, UPDATE ON STOCKS TO SENIOR_SALESMAN;
GRANT SELECT ON STAFF_SALE_ACT TO SENIOR_SALESMAN;

----------------------
-- Salesman Manager --
----------------------

CREATE VIEW STAFF_SALE AS
SELECT staff_id, first_name, last_name, email, phone, store_id, manager_id
FROM ADMIN.STAFFS
WHERE department = 'SALESMAN';

GRANT SENIOR_SALESMAN TO SALESMAN_MANAGER;
GRANT SELECT ON STAFF_SALE TO SALESMAN_MANAGER;
GRANT SELECT ON PRODUCTS TO SALESMAN_MANAGER;

-------------------------
-- Junior Warehouseman --
-------------------------

CREATE VIEW CUSTOMER_WO_ADDRESS AS
SELECT customer_id, first_name, last_name, phone, email
FROM CUSTOMERS;

GRANT SELECT ON CATEGORIES TO JUNIOR_WAREHOUSEMAN;
GRANT SELECT ON BRANDS TO JUNIOR_WAREHOUSEMAN;
GRANT SELECT ON PRODUCTS TO JUNIOR_WAREHOUSEMAN;
GRANT SELECT ON CUSTOMER_WO_ADDRESS TO JUNIOR_WAREHOUSEMAN;

-------------------------
-- Senior Warehouseman --
-------------------------

CREATE VIEW STAFF_WAREHOUSE_ACT AS
SELECT staff_id, first_name, last_name, email, phone, store_id, manager_id
FROM ADMIN.STAFFS
WHERE active = 1
  AND department = 'WAREHOUSEMAN';

GRANT SELECT, UPDATE ON STOCKS TO SENIOR_WAREHOUSEMAN;
GRANT SELECT ON STAFF_WAREHOUSE_ACT TO SENIOR_WAREHOUSEMAN;

--------------------------
-- Warehouseman Manager --
--------------------------

CREATE VIEW STAFF_WAREHOUSE AS
SELECT staff_id, first_name, last_name, email, phone, store_id, manager_id
FROM ADMIN.STAFFS
WHERE department = 'SALESMAN';

GRANT SELECT ON STAFF_WAREHOUSE TO WAREHOUSEMAN_MANAGER;
GRANT SELECT, INSERT, UPDATE ON BRANDS TO WAREHOUSEMAN_MANAGER;
GRANT SELECT, INSERT, UPDATE ON CATEGORIES TO WAREHOUSEMAN_MANAGER;
GRANT SELECT, INSERT, UPDATE ON PRODUCTS TO WAREHOUSEMAN_MANAGER;

-----------------
-- Top Manager --
-----------------

GRANT SELECT, INSERT, UPDATE ON STAFFS TO TOPMANAGER;
GRANT SELECT, INSERT, UPDATE ON STORES TO TOPMANAGER;
